version: '3'
services: 
  vivliostyle:
      container_name: vivliostyle
      build:
          context: ./Docker/Ubuntu
      ports:
          - "6080:80"
      volumes:
          - "./src:/src"
      working_dir: /src
      tty: true